# Generated by Django 6.0.1 on 2026-09-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Маркировка / Размер')),
                ('total_length', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая длина (м)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество (шт)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-updated_at'],
            },
        ),
    ]
