# Generated by Django 6.0.1 on 2026-09-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saw_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='total_length',
        ),
    ]
